import { models } from "../config/db.js";

export const ASSOCIATION_MAP = {
    scan_vulnerabilities: {
        model: models.scan_vulnerabilities,
        as: "scan_vulnerabilities",
        attributes: [
            "id",
            "scan_id",
            "cve_id",
            "package_name",
            "package_version",
            "severity",
            "score",
            "vector",
            "description",
            "discovered_at",
            "source",
            "agent_id",
            "tenant_id",
        ],
        required: false,
        include: [
            {
                model: models.scans,
                as: "scan",
                attributes: [
                    "id",
                    "agent_id",
                    "scan_start",
                    "scan_end",
                    "status",
                    "packages_scanned",
                    "vulnerabilities_found",
                    "scan_duration",
                    "analysis_mode",
                    "tenant_id",
                ],
                required: false,
                include: [
                    {
                        model: models.agents,
                        as: "agent",
                        attributes: [
                            "id",
                            "agent_id",
                            "hostname",
                            "platform",
                            "architecture",
                            "agent_version",
                            "first_seen",
                            "last_seen",
                            "status",
                            "tenant_id",
                        ],
                        required: false,
                        include: [
                            {
                                model: models.tenants,
                                as: "tenants",
                                attributes: ["id", "name", "status"],
                                required: false,
                            },
                        ],
                    },
                ],
            },
            {
                model: models.cves,
                as: "cve",
                attributes: [
                    "cve_id",
                    "source_id",
                    "description",
                    "severity",
                    "cvss_v2_score",
                    "cvss_v3_score",
                    "cvss_v2_vector",
                    "cvss_v3_vector",
                    "cvss_v4_score",
                    "cvss_v4_vector",
                    "published_date",
                    "modified_date",
                    "discovered_by_source",
                    "source_priority",
                    "cross_source_verified",
                    "mitigation",
                ],
                required: false,
                include: [
                    {
                        model: models.vulnerability_sources,
                        as: "source",
                        attributes: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "last_fetch_status"],
                        required: false,
                    },
                    {
                        model: models.cve_attack_mappings,
                        as: "cve_attack_mappings",
                        attributes: ["id", "technique_id", "confidence_level", "mapping_source"],
                        required: false,
                        include: [
                            {
                                model: models.mitre_techniques,
                                as: "technique",
                                attributes: ["technique_id", "name", "description"],
                                required: false,
                            },
                        ],
                    },
                ],
            },
            {
                model: models.tenants,
                as: "tenants",
                attributes: ["id", "name", "status"],
                required: false,
            },
        ],
    },
    scans: {
        model: models.scans,
        as: "scans",
        attributes: [
            "id",
            "agent_id",
            "scan_start",
            "scan_end",
            "status",
            "packages_scanned",
            "vulnerabilities_found",
            "scan_duration",
            "analysis_mode",
            "tenant_id",
        ],
        required: false,
        include: [
            {
                model: models.agents,
                as: "agent",
                attributes: [
                    "id",
                    "agent_id",
                    "hostname",
                    "platform",
                    "architecture",
                    "agent_version",
                    "first_seen",
                    "last_seen",
                    "status",
                    "tenant_id",
                ],
                required: false,
                include: [
                    {
                        model: models.tenants,
                        as: "tenants",
                        attributes: ["id", "name", "status"],
                        required: false,
                    },
                ],
            },
            {
                model: models.tenants,
                as: "tenants",
                attributes: ["id", "name", "status"],
                required: false,
            },
        ],
    },
    agents: {
        model: models.agents,
        as: "agents",
        attributes: [
            "id",
            "agent_id",
            "hostname",
            "platform",
            "architecture",
            "agent_version",
            "metadata",
            "first_seen",
            "last_seen",
            "status",
            "tenant_id",
        ],
        required: false,
        include: [
            {
                model: models.tenants,
                as: "tenants",
                attributes: ["id", "name", "status"],
                required: false,
            },
        ],
    },
    cves: {
        model: models.cves,
        as: "cves",
        attributes: [
            "cve_id",
            "source_id",
            "description",
            "severity",
            "cvss_v2_score",
            "cvss_v3_score",
            "cvss_v2_vector",
            "cvss_v3_vector",
            "cvss_v4_score",
            "cvss_v4_vector",
            "published_date",
            "modified_date",
            "discovered_by_source",
            "source_priority",
            "cross_source_verified",
            "mitigation",
        ],
        required: false,
        include: [
            {
                model: models.vulnerability_sources,
                as: "source",
                attributes: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "last_fetch_status"],
                required: false,
            },
            {
                model: models.cve_attack_mappings,
                as: "cve_attack_mappings",
                attributes: ["id", "technique_id", "confidence_level", "mapping_source"],
                required: false,
                include: [
                    {
                        model: models.mitre_techniques,
                        as: "technique",
                        attributes: ["technique_id", "name", "description"],
                        required: false,
                    },
                ],
            },
        ],
    },
    vulnerability_sources: {
        model: models.vulnerability_sources,
        as: "vulnerability_sources",
        attributes: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "last_fetch_status"],
        required: false,
    },
    cve_attack_mappings: {
        model: models.cve_attack_mappings,
        as: "cve_attack_mappings",
        attributes: ["id", "cve_id", "technique_id", "confidence_level", "mapping_source"],
        required: false,
        include: [
            {
                model: models.mitre_techniques,
                as: "technique",
                attributes: ["technique_id", "name", "description"],
                required: false,
            },
        ],
    },
    mitre_techniques: {
        model: models.mitre_techniques,
        as: "mitre_techniques",
        attributes: ["technique_id", "name", "description"],
        required: false,
    },
    android_cve: {
        model: models.android_cve,
        as: "android_cves",
        attributes: ["cve_id", "advisory_id", "description", "severity", "type", "reference", "updated_aosp_versions"],
        required: false,
        include: [
            {
                model: models.android_advisory,
                as: "advisory",
                attributes: ["advisory_id", "bulletin_url", "bulletin_title", "bulletin_date"],
                required: false,
            },
        ],
    },
    android_advisory: {
        model: models.android_advisory,
        as: "android_advisories",
        attributes: ["advisory_id", "bulletin_url", "bulletin_title", "bulletin_date"],
        required: false,
    },
    ios_cve: {
        model: models.ios_cve,
        as: "ios_cves",
        attributes: ["cve_id", "description"],
        required: false,
        include: [
            {
                model: models.ios_advisory_cve,
                as: "ios_advisory_cves",
                attributes: ["advisory_id", "cve_id"],
                required: false,
                include: [
                    {
                        model: models.ios_advisory,
                        as: "advisory",
                        attributes: ["advisory_id", "advisory_url", "advisory_title", "advisory_date", "product"],
                        required: false,
                    },
                ],
            },
            {
                model: models.ios_update_cve,
                as: "ios_update_cves",
                attributes: ["update_id", "cve_id"],
                required: false,
                include: [
                    {
                        model: models.ios_update,
                        as: "update",
                        attributes: ["update_id", "update_version", "release_date", "product", "update_url"],
                        required: false,
                    },
                ],
            },
        ],
    },
    ios_advisory: {
        model: models.ios_advisory,
        as: "ios_advisories",
        attributes: ["advisory_id", "advisory_url", "advisory_title", "advisory_date", "product", "summary"],
        required: false,
    },
    ios_advisory_cve: {
        model: models.ios_advisory_cve,
        as: "ios_advisory_cves",
        attributes: ["advisory_id", "cve_id"],
        required: false,
        include: [
            {
                model: models.ios_advisory,
                as: "advisory",
                attributes: ["advisory_id", "advisory_url", "advisory_title", "advisory_date", "product"],
                required: false,
            },
            {
                model: models.ios_cve,
                as: "cve",
                attributes: ["cve_id", "description"],
                required: false,
            },
        ],
    },
    ios_update: {
        model: models.ios_update,
        as: "ios_updates",
        attributes: ["update_id", "update_version", "release_date", "product", "update_url"],
        required: false,
    },
    ios_update_cve: {
        model: models.ios_update_cve,
        as: "ios_update_cves",
        attributes: ["update_id", "cve_id"],
        required: false,
        include: [
            {
                model: models.ios_update,
                as: "update",
                attributes: ["update_id", "update_version", "release_date", "product", "update_url"],
                required: false,
            },
            {
                model: models.ios_cve,
                as: "cve",
                attributes: ["cve_id", "description"],
                required: false,
            },
        ],
    },
    windows_cve: {
        model: models.windows_cve,
        as: "windows_cves",
        attributes: ["cve_id", "cve_title", "cve_description", "severity", "cvss_score", "cvss_vector", "remediation", "threat_info"],
        required: false,
        include: [
            {
                model: models.windows_advisory_cve,
                as: "windows_advisory_cves",
                attributes: ["advisory_id", "cve_id"],
                required: false,
                include: [
                    {
                        model: models.windows_advisory,
                        as: "advisory",
                        attributes: [
                            "advisory_id",
                            "advisory_tracking_id",
                            "advisory_title",
                            "initial_release_date",
                            "current_release_date",
                            "status",
                            "reference_urls",
                        ],
                        required: false,
                    },
                ],
            },
            {
                model: models.windows_cve_product,
                as: "windows_cve_products",
                attributes: ["cve_id", "product_id"],
                required: false,
                include: [
                    {
                        model: models.windows_product,
                        as: "product",
                        attributes: ["product_id", "product_name"],
                        required: false,
                    },
                ],
            },
        ],
    },
    windows_advisory: {
        model: models.windows_advisory,
        as: "windows_advisories",
        attributes: [
            "advisory_id",
            "advisory_tracking_id",
            "advisory_title",
            "initial_release_date",
            "current_release_date",
            "status",
            "reference_urls",
        ],
        required: false,
    },
    windows_advisory_cve: {
        model: models.windows_advisory_cve,
        as: "windows_advisory_cves",
        attributes: ["advisory_id", "cve_id"],
        required: false,
        include: [
            {
                model: models.windows_advisory,
                as: "advisory",
                attributes: [
                    "advisory_id",
                    "advisory_tracking_id",
                    "advisory_title",
                    "initial_release_date",
                    "current_release_date",
                    "status",
                    "reference_urls",
                ],
                required: false,
            },
            {
                model: models.windows_cve,
                as: "cve",
                attributes: ["cve_id", "cve_title", "cve_description", "severity", "cvss_score", "cvss_vector", "remediation", "threat_info"],
                required: false,
            },
        ],
    },
    windows_product: {
        model: models.windows_product,
        as: "windows_products",
        attributes: ["product_id", "product_name"],
        required: false,
    },
    windows_cve_product: {
        model: models.windows_cve_product,
        as: "windows_cve_products",
        attributes: ["cve_id", "product_id"],
        required: false,
        include: [
            {
                model: models.windows_cve,
                as: "cve",
                attributes: ["cve_id", "cve_title", "cve_description", "severity", "cvss_score", "cvss_vector", "remediation", "threat_info"],
                required: false,
            },
            {
                model: models.windows_product,
                as: "product",
                attributes: ["product_id", "product_name"],
                required: false,
            },
        ],
    },
    cve_update_marker: {
        model: models.cve_update_marker,
        as: "cve_update_markers",
        attributes: ["source_id", "latest_cve_id", "updated_at", "tenant_id"],
        required: false,
        include: [
            {
                model: models.vulnerability_sources,
                as: "source",
                attributes: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "last_fetch_status"],
                required: false,
            },
            {
                model: models.tenants,
                as: "tenants",
                attributes: ["id", "name", "status"],
                required: false,
            },
        ],
    },
    quality_metrics: {
        model: models.quality_metrics,
        as: "quality_metrics",
        attributes: [
            "id",
            "pipeline_run_id",
            "source_id",
            "completeness_score",
            "accuracy_score",
            "consistency_score",
            "timeliness_score",
            "validity_score",
            "total_records",
            "valid_records",
            "duplicate_records",
            "invalid_records",
            "missing_critical_fields",
        ],
        required: false,
        include: [
            {
                model: models.pipeline_executions,
                as: "pipeline_run",
                attributes: ["run_id", "pipeline_type", "execution_status", "started_at", "completed_at"],
                required: false,
            },
            {
                model: models.vulnerability_sources,
                as: "source",
                attributes: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "last_fetch_status"],
                required: false,
            },
        ],
    },
    source_fetch_audit: {
        model: models.source_fetch_audit,
        as: "source_fetch_audits",
        attributes: [
            "id",
            "source_id",
            "pipeline_run_id",
            "fetch_started",
            "fetch_completed",
            "status",
            "records_available",
            "records_fetched",
            "records_new",
            "records_updated",
            "records_duplicated",
            "records_skipped",
            "fetch_quality_score",
            "parsing_errors",
            "validation_errors",
            "fetch_duration_seconds",
            "parse_duration_seconds",
            "load_duration_seconds",
            "api_calls_made",
            "data_transferred_mb",
            "rate_limit_hits",
            "error_message",
            "retry_attempts",
        ],
        required: false,
        include: [
            {
                model: models.vulnerability_sources,
                as: "source",
                attributes: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "last_fetch_status"],
                required: false,
            },
            {
                model: models.pipeline_executions,
                as: "pipeline_run",
                attributes: ["run_id", "pipeline_type", "execution_status", "started_at", "completed_at"],
                required: false,
            },
        ],
    },
    pkg_database: {
        model: models.pkg_database,
        as: "pkg_databases",
        attributes: [
            "id",
            "pkg_name",
            "vendor",
            "version",
            "architecture",
            "description",
            "source",
            "status",
            "release",
            "dependencies",
            "homepage",
            "repository",
            "cve_list",
            "fixed_version",
            "tenant_id",
        ],
        required: false,
        include: [
            {
                model: models.tenants,
                as: "tenants",
                attributes: ["id", "name", "status"],
                required: false,
            },
        ],
    },
    pipeline_executions: {
        model: models.pipeline_executions,
        as: "pipeline_executions",
        attributes: [
            "run_id",
            "pipeline_type",
            "execution_status",
            "started_at",
            "completed_at",
            "triggered_by",
            "environment",
            "source_filters",
            "total_sources",
            "completed_sources",
            "failed_sources",
            "total_vulnerabilities_processed",
            "data_quality_score",
            "validation_errors",
            "duplicate_count",
            "execution_time_seconds",
            "memory_usage_mb",
            "cpu_usage_percent",
            "error_message",
            "retry_count",
            "created_by",
        ],
        required: false,
    },
    tenants: {
        model: models.tenants,
        as: "tenants",
        attributes: ["id", "name", "description", "status", "plan", "contact_email", "region"],
        required: false,
    },
    users: {
        model: models.users,
        as: "users",
        attributes: ["id", "email", "name_first", "name_last", "status", "last_login"],
        required: false,
    },
};
