export const JOIN_SCHEMA = {
    tenant: {
        alias: "t",
        table: "tenants",
        type: "INNER JOIN",
        on: (parentAlias) => `${parentAlias}.tenant_id = t.id`,
        columns: ["id", "name", "status", "plan", "region", "contact_email", "created_at"],
    },
    user: {
        alias: "u",
        table: "users",
        type: "INNER JOIN",
        on: (parentAlias) => `${parentAlias}.user_id = u.id`,
        columns: ["id", "email", "name_first", "name_last", "status", "last_login", "created_at"],
    },
    tenant_user: {
        alias: "tu",
        table: "tenant_users",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.tenant_id = tu.tenant_id AND ${parentAlias}.user_id = tu.user_id`,
        columns: ["tenant_id", "user_id", "role_id", "status", "created_at"],
    },

    role: {
        alias: "r",
        table: "roles",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.role_id = r.id`,
        columns: ["id", "name", "description", "tenant_scoped", "created_at"],
    },
    permission: {
        alias: "p",
        table: "permissions",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.permission_key = p.key`,
        columns: ["key", "feature", "action", "description", "tenant_scoped", "created_at"],
    },
    role_permission: {
        alias: "rp",
        table: "role_permissions",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.role_id = rp.role_id AND ${parentAlias}.permission_key = rp.permission_key`,
        columns: ["role_id", "permission_key", "created_at"],
    },
    user_role: {
        alias: "ur",
        table: "user_roles",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.user_id = ur.user_id AND ${parentAlias}.role_id = ur.role_id`,
        columns: ["user_id", "role_id", "created_at"],
    },

    user_session: {
        alias: "sess",
        table: "user_sessions",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.user_id = sess.user_id`,
        columns: ["id", "token", "ip_address", "user_agent", "login_method", "expires_at", "revoked", "created_at"],
    },
    audit_log: {
        alias: "al",
        table: "audit_logs",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.id = al.id`,
        columns: ["tenant_id", "user_id", "action", "entity_type", "entity_id", "ip_address", "response_status", "created_at"],
    },

    notification_setting: {
        alias: "ns",
        table: "notification_settings",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.id = ns.id`,
        columns: ["tenant_id", "user_id", "enabled", "email_enabled", "webhook_enabled", "created_at"],
    },
    notification: {
        alias: "n",
        table: "notifications",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.id = n.id`,
        columns: ["tenant_id", "user_id", "title", "body", "category", "severity_score", "read", "created_at"],
    },
    notification_rule: {
        alias: "nr",
        table: "notification_rules",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.settings_id = nr.settings_id`,
        columns: ["settings_id", "rule_name", "rule_enabled", "created_at"],
    },

    system_setting: {
        alias: "ss",
        table: "system_settings",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.tenant_id = ss.tenant_id`,
        columns: ["key", "value", "description", "created_at"],
    },
    platform_setting: {
        alias: "ps",
        table: "platform_settings",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.id = ps.id`,
        columns: ["key", "value", "description", "created_at"],
    },

    agent: {
        alias: "ag",
        table: "agents",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.agent_id = ag.agent_id`,
        columns: ["id", "hostname", "platform", "architecture", "status", "last_seen", "tenant_id", "created_at"],
    },
    scan: {
        alias: "sc",
        table: "scans",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.scan_id = sc.id`,
        columns: ["id", "agent_id", "scan_start", "scan_end", "status", "vulnerabilities_found", "tenant_id", "created_at"],
    },
    scan_vulnerability: {
        alias: "sv",
        table: "scan_vulnerabilities",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.id = sv.id`,
        columns: ["scan_id", "cve_id", "package_name", "package_version", "severity", "score", "agent_id", "tenant_id", "created_at"],
    },

    asset: {
        alias: "a",
        table: "assets",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.asset_id = a.id`,
        columns: ["id", "name", "resource_id", "resource_type", "provider", "region", "environment", "lifecycle_state", "tenant_id", "created_at"],
    },
    asset_tag: {
        alias: "at",
        table: "asset_tags",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.asset_id = at.asset_id`,
        columns: ["asset_id", "tag_key", "tag_value", "created_at"],
    },
    policy: {
        alias: "pol",
        table: "policies",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.policy_id = pol.id`,
        columns: ["id", "name", "description", "category", "compliance_status", "tenant_id", "created_at"],
    },
    compliance: {
        alias: "comp",
        table: "compliance",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.compliance_id = comp.id`,
        columns: ["id", "framework", "control_id", "control_title", "status", "severity", "tenant_id", "last_checked_at"],
    },
    report: {
        alias: "rep",
        table: "reports",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.report_id = rep.id`,
        columns: ["id", "title", "type", "status", "tenant_id", "generated_at", "created_at"],
    },
    threat: {
        alias: "th",
        table: "threats",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.threat_id = th.id`,
        columns: ["id", "name", "severity", "status", "description", "tenant_id", "created_at"],
    },

    asset_threat: {
        alias: "at_rel",
        table: "asset_threats",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.asset_id = at_rel.asset_id AND ${parentAlias}.threat_id = at_rel.threat_id`,
        columns: ["asset_id", "threat_id", "created_at"],
    },
    asset_compliance: {
        alias: "ac_rel",
        table: "asset_compliance",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.asset_id = ac_rel.asset_id AND ${parentAlias}.compliance_id = ac_rel.compliance_id`,
        columns: ["asset_id", "compliance_id", "created_at"],
    },
    policy_asset: {
        alias: "pa_rel",
        table: "policy_assets",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.policy_id = pa_rel.policy_id AND ${parentAlias}.asset_id = pa_rel.asset_id`,
        columns: ["policy_id", "asset_id", "created_at"],
    },
    policy_compliance: {
        alias: "pc_rel",
        table: "policy_compliance",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.policy_id = pc_rel.policy_id AND ${parentAlias}.compliance_id = pc_rel.compliance_id`,
        columns: ["policy_id", "compliance_id", "created_at"],
    },
    report_asset: {
        alias: "ra_rel",
        table: "report_assets",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.report_id = ra_rel.report_id AND ${parentAlias}.asset_id = ra_rel.asset_id`,
        columns: ["report_id", "asset_id", "created_at"],
    },
    report_policy: {
        alias: "rpol_rel",
        table: "report_policies",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.report_id = rpol_rel.report_id AND ${parentAlias}.policy_id = rpol_rel.policy_id`,
        columns: ["report_id", "policy_id", "created_at"],
    },
    report_compliance: {
        alias: "rc_rel",
        table: "report_compliance",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.report_id = rc_rel.report_id AND ${parentAlias}.compliance_id = rc_rel.compliance_id`,
        columns: ["report_id", "compliance_id", "created_at"],
    },
    threat_remediation: {
        alias: "tr_step",
        table: "threat_remediation_steps",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.threat_id = tr_step.threat_id`,
        columns: ["threat_id", "step_order", "step_description", "created_at"],
    },
    compliance_remediation: {
        alias: "cr_step",
        table: "compliance_remediation_steps",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.compliance_id = cr_step.compliance_id`,
        columns: ["compliance_id", "step_order", "step_description", "created_at"],
    },
    threat_finding: {
        alias: "tf_rel",
        table: "threat_related_findings",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.threat_id = tf_rel.threat_id`,
        columns: ["threat_id", "finding_id", "created_at"],
    },

    cve: {
        alias: "c",
        table: "cves",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.cve_id = c.cve_id`,
        columns: [
            "cve_id",
            "source_id",
            "description",
            "severity",
            "cvss_v2_score",
            "cvss_v3_score",
            "cvss_v4_score",
            "published_date",
            "modified_date",
            "created_at",
        ],
    },
    vulnerability_source: {
        alias: "vs",
        table: "vulnerability_sources",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.source_id = vs.id`,
        columns: ["id", "source_name", "display_name", "category", "status", "priority", "last_fetch_at", "created_at"],
    },
    cve_attack_mapping: {
        alias: "cam",
        table: "cve_attack_mappings",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.cve_id = cam.cve_id`,
        columns: ["cve_id", "technique_id", "confidence_level", "mapping_source", "created_at"],
    },
    mitre_technique: {
        alias: "mt",
        table: "mitre_techniques",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.technique_id = mt.technique_id`,
        columns: ["technique_id", "name", "description", "created_at"],
    },

    android_advisory: {
        alias: "aa",
        table: "android_advisory",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.advisory_id = aa.advisory_id`,
        columns: ["advisory_id", "bulletin_url", "bulletin_title", "bulletin_date", "created_at"],
    },
    android_cve: {
        alias: "ac",
        table: "android_cve",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.cve_id = ac.cve_id`,
        columns: ["cve_id", "advisory_id", "severity", "type", "updated_aosp_versions", "created_at"],
    },
    ios_advisory: {
        alias: "ia",
        table: "ios_advisory",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.advisory_id = ia.advisory_id`,
        columns: ["advisory_id", "advisory_url", "advisory_title", "advisory_date", "product", "created_at"],
    },
    ios_cve: {
        alias: "ic",
        table: "ios_cve",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.cve_id = ic.cve_id`,
        columns: ["cve_id", "description", "created_at"],
    },
    ios_update: {
        alias: "iu",
        table: "ios_update",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.update_id = iu.update_id`,
        columns: ["update_id", "update_version", "release_date", "product", "created_at"],
    },
    ios_advisory_cve: {
        alias: "iac",
        table: "ios_advisory_cve",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.advisory_id = iac.advisory_id AND ${parentAlias}.cve_id = iac.cve_id`,
        columns: ["advisory_id", "cve_id", "created_at"],
    },
    ios_update_cve: {
        alias: "iuc",
        table: "ios_update_cve",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.update_id = iuc.update_id AND ${parentAlias}.cve_id = iuc.cve_id`,
        columns: ["update_id", "cve_id", "created_at"],
    },
    windows_advisory: {
        alias: "wa",
        table: "windows_advisory",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.advisory_id = wa.advisory_id`,
        columns: ["advisory_id", "advisory_tracking_id", "advisory_title", "initial_release_date", "status", "created_at"],
    },
    windows_cve: {
        alias: "wc",
        table: "windows_cve",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.cve_id = wc.cve_id`,
        columns: ["cve_id", "cve_title", "severity", "cvss_score", "remediation", "created_at"],
    },
    windows_product: {
        alias: "wp",
        table: "windows_product",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.product_id = wp.product_id`,
        columns: ["product_id", "product_name", "created_at"],
    },
    windows_advisory_cve: {
        alias: "wac",
        table: "windows_advisory_cve",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.advisory_id = wac.advisory_id AND ${parentAlias}.cve_id = wac.cve_id`,
        columns: ["advisory_id", "cve_id", "created_at"],
    },
    windows_cve_product: {
        alias: "wcp",
        table: "windows_cve_product",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.cve_id = wcp.cve_id AND ${parentAlias}.product_id = wcp.product_id`,
        columns: ["cve_id", "product_id", "created_at"],
    },

    pkg_database: {
        alias: "pkg",
        table: "pkg_database",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.pkg_name = pkg.pkg_name AND ${parentAlias}.tenant_id = pkg.tenant_id`,
        columns: ["id", "pkg_name", "vendor", "version", "architecture", "description", "cve_list", "fixed_version", "tenant_id", "created_at"],
    },
    vsa_database: {
        alias: "vsa",
        table: "vsa_database",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.id = vsa.id`,
        columns: ["advisory_id", "advisory_title", "cve_list", "severity", "cvss_score", "published_date", "status_advisory", "created_at"],
    },

    cloud_connector: {
        alias: "cc",
        table: "cloud_connectors",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.connector_id = cc.id`,
        columns: ["id", "name", "provider", "status", "health_status", "tenant_id", "created_at"],
    },
    connector_health_issue: {
        alias: "chi",
        table: "connector_health_issues",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.connector_id = chi.connector_id`,
        columns: ["connector_id", "issue_description", "severity", "resolved", "resolved_at", "created_at"],
    },

    pipeline_execution: {
        alias: "pe",
        table: "pipeline_executions",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.pipeline_run_id = pe.run_id`,
        columns: [
            "run_id",
            "pipeline_type",
            "execution_status",
            "started_at",
            "completed_at",
            "total_vulnerabilities_processed",
            "data_quality_score",
            "created_at",
        ],
    },
    quality_metric: {
        alias: "qm",
        table: "quality_metrics",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.pipeline_run_id = qm.pipeline_run_id AND ${parentAlias}.source_id = qm.source_id`,
        columns: ["pipeline_run_id", "source_id", "completeness_score", "accuracy_score", "total_records", "valid_records", "created_at"],
    },
    source_fetch_audit: {
        alias: "sfa",
        table: "source_fetch_audit",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.pipeline_run_id = sfa.pipeline_run_id AND ${parentAlias}.source_id = sfa.source_id`,
        columns: ["source_id", "pipeline_run_id", "fetch_started", "status", "records_fetched", "fetch_quality_score", "error_message", "created_at"],
    },
    cve_update_marker: {
        alias: "cum",
        table: "cve_update_marker",
        type: "LEFT JOIN",
        on: (parentAlias) => `${parentAlias}.source_id = cum.source_id AND ${parentAlias}.tenant_id = cum.tenant_id`,
        columns: ["source_id", "latest_cve_id", "tenant_id", "updated_at", "created_at"],
    },
};
